name: Check UMFA Product Availability

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch: # Allows manual runs

jobs:
  check-product:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios cheerio nodemailer dotenv

      - name: Run Check Script
        run: node check.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
